// <auto-generated />
using System;
using DixseptData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DixseptData.Migrations
{
    [DbContext(typeof(DixseptContext))]
    [Migration("20210907141943_addColumn_player")]
    partial class addColumn_player
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DixseptData.Entity.M_PLAYER", b =>
                {
                    b.Property<int>("PLAYER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BIRTHDAY")
                        .HasColumnType("Date");

                    b.Property<string>("BIRTH_PLACE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRST_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRST_NAME_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HEIGHT")
                        .HasColumnType("int");

                    b.Property<string>("LAST_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAST_NAME_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLAYER_IMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLAYER_IMG_OLD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION_CD")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("UNIFORM_NUMBER")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WEIGHT")
                        .HasColumnType("int");

                    b.HasKey("PLAYER_ID");

                    b.ToTable("M_PLAYER");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.M_POSITION", b =>
                {
                    b.Property<string>("POSITION_CD")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("POSITION_CD");

                    b.ToTable("M_POSITION");

                    b.HasData(
                        new
                        {
                            POSITION_CD = "1",
                            POSITION_NAME = "Goleiro"
                        },
                        new
                        {
                            POSITION_CD = "2",
                            POSITION_NAME = "Fixo"
                        },
                        new
                        {
                            POSITION_CD = "3",
                            POSITION_NAME = "Ala"
                        },
                        new
                        {
                            POSITION_CD = "4",
                            POSITION_NAME = "Pivo"
                        });
                });

            modelBuilder.Entity("DixseptData.Entity.Table.M_TEAM", b =>
                {
                    b.Property<int>("TEAM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMBLEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TEAM_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TEAM_ID");

                    b.ToTable("M_TEAM");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.M_TOURNAMENT", b =>
                {
                    b.Property<int>("TOURNAMENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEASON_YEAR")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TOUNAMENT_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TOURNAMENT_ID");

                    b.ToTable("M_TOURNAMENT");

                    b.HasData(
                        new
                        {
                            TOURNAMENT_ID = 1,
                            SEASON_YEAR = "2021",
                            TOUNAMENT_NAME = "埼玉県フットサル2部リーグ"
                        },
                        new
                        {
                            TOURNAMENT_ID = 2,
                            SEASON_YEAR = "2022",
                            TOUNAMENT_NAME = "埼玉県フットサル2部リーグ"
                        },
                        new
                        {
                            TOURNAMENT_ID = 3,
                            SEASON_YEAR = "2023",
                            TOUNAMENT_NAME = "埼玉県フットサル2部リーグ"
                        },
                        new
                        {
                            TOURNAMENT_ID = 4,
                            SEASON_YEAR = "2021",
                            TOUNAMENT_NAME = "全日本フットサル選手権大会埼玉県大会"
                        },
                        new
                        {
                            TOURNAMENT_ID = 5,
                            SEASON_YEAR = "2022",
                            TOUNAMENT_NAME = "全日本フットサル選手権大会埼玉県大会"
                        });
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_NEWS", b =>
                {
                    b.Property<int>("NEWS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NEWS_CD")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NEWS_IMG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OFFICIAL_SCHEDULE_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PRACTICE_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PRACTICE_SCHEDULE_ID")
                        .HasColumnType("int");

                    b.Property<string>("TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NEWS_ID");

                    b.ToTable("T_NEWS");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_OFFICIAL_POINT", b =>
                {
                    b.Property<int>("OFFICIAL_POINT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OFFICIAL_RESULT_ID")
                        .HasColumnType("int");

                    b.Property<int>("PLAYER_ID")
                        .HasColumnType("int");

                    b.Property<bool>("POINT_CD")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OFFICIAL_POINT_ID");

                    b.ToTable("T_OFFICIAL_POINT");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_OFFICIAL_RESULT", b =>
                {
                    b.Property<int>("OFFICIAL_RESULT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("A_EX_FIRST_TIME")
                        .HasColumnType("int");

                    b.Property<int?>("A_EX_LAST_TIME")
                        .HasColumnType("int");

                    b.Property<int>("A_FIRST_TIME")
                        .HasColumnType("int");

                    b.Property<int?>("A_PK")
                        .HasColumnType("int");

                    b.Property<int>("A_SECOND_TIME")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("H_EX_FIRST_TIME")
                        .HasColumnType("int");

                    b.Property<int?>("H_EX_LAST_TIME")
                        .HasColumnType("int");

                    b.Property<int>("H_FIRST_TIME")
                        .HasColumnType("int");

                    b.Property<int?>("H_PK")
                        .HasColumnType("int");

                    b.Property<int>("H_SECOND_TIME")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OFFICIAL_RESULT_ID");

                    b.ToTable("T_OFFICIAL_RESULT");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_OFFICIAL_SCHEDULE", b =>
                {
                    b.Property<int>("OFFICIAL_SCHEDULE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CATEGORY")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("Date");

                    b.Property<int>("OPPONENT_ID")
                        .HasColumnType("int");

                    b.Property<string>("PLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SECTION")
                        .HasColumnType("int");

                    b.Property<string>("TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TOURNAMENT_ID")
                        .HasColumnType("int");

                    b.HasKey("OFFICIAL_SCHEDULE_ID");

                    b.ToTable("T_OFFICIAL_SCHEDULE");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_PRACTICEGAME_DETAIL", b =>
                {
                    b.Property<int>("PRACTICE_DETAIL_RESULT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GAME_COUNT")
                        .HasColumnType("int");

                    b.Property<int>("GAME_TIME")
                        .HasColumnType("int");

                    b.Property<int>("PRACTICEGAME_ID")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRACTICE_DETAIL_RESULT_ID");

                    b.ToTable("T_PRACTICEGAME_DETAIL");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_PRACTICEGAME_POINT", b =>
                {
                    b.Property<int>("PRACTICE_POINT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PLAYER_ID")
                        .HasColumnType("int");

                    b.Property<string>("POINT_CD")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("PRACTICEGAME_DETAIL_ID")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRACTICE_POINT_ID");

                    b.ToTable("T_PRACTICEGAME_POINT");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_PRACTICEGAME_SCHEDULE", b =>
                {
                    b.Property<int>("PRACTICEGAME_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CATEGORY")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("Date");

                    b.Property<string>("OPPONENT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLACE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRACTICEGAME_ID");

                    b.ToTable("T_PRACTICEGAME_SCHEDULE");
                });

            modelBuilder.Entity("DixseptData.Entity.Table.T_PRACTICE_SCHEDULE", b =>
                {
                    b.Property<int>("PRACTICE_SCHEDULE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CATEGORY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("Date");

                    b.Property<string>("TIME")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<byte[]>("Timestamp")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UPDATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATE_BY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PRACTICE_SCHEDULE_ID");

                    b.ToTable("T_PRACTICE_SCHEDULE");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
